/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import formulabean.FormulaBean;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.EquipF1;

/**
 *
 * @author alumne
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        // Codi d'inicialitzacio (s'executa al principi de l'aplicacio)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulaBean1 = new formulabean.FormulaBean();
        jPanelExtern = new javax.swing.JPanel();
        jPanelDades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextEquip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextNumMecanics = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPressupost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBoxCampio = new javax.swing.JCheckBox();
        jButtonInsertar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextDorsal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextNomPilot = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextEmailPilot = new javax.swing.JTextField();
        jButtonInsertPilot = new javax.swing.JButton();
        jButtonModificaPilot = new javax.swing.JButton();
        jButtonBorraPilot = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonMostrarTotsEquips = new javax.swing.JButton();
        jComboBoxOrdenar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelExtern.setBackground(java.awt.Color.lightGray);

        jPanelDades.setBackground(java.awt.Color.white);
        jPanelDades.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Equip");

        jTextEquip.setText("jTextField1");

        jLabel2.setText("Número mecanics");

        jTextNumMecanics.setText("jTextField1");

        jLabel3.setText("Pressupost");

        jTextPressupost.setText("jTextField1");

        jLabel5.setText("Campió mundial");

        jButtonInsertar.setText("Insertar");

        jButtonBorrar.setText("Borrar");

        jButtonModificar.setText("Modificar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equip", "Num mecanics", "Campió mundial", "Pressupost"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Dorsal");

        jTextDorsal.setText("jTextField1");

        jLabel4.setText("Nom Pilot");

        jTextNomPilot.setText("jTextField1");
        jTextNomPilot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomPilotActionPerformed(evt);
            }
        });

        jLabel6.setText("Email");

        jTextEmailPilot.setText("jTextField1");

        jButtonInsertPilot.setText("Insertar");

        jButtonModificaPilot.setText("Modificar");

        jButtonBorraPilot.setText("Borrar");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dorsal", "Nom", "Email"
            }
        ));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(jTable2);

        jButtonMostrarTotsEquips.setText("Mostrar tots els pilots");
        jButtonMostrarTotsEquips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarTotsEquipsActionPerformed(evt);
            }
        });

        jComboBoxOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelDadesLayout = new javax.swing.GroupLayout(jPanelDades);
        jPanelDades.setLayout(jPanelDadesLayout);
        jPanelDadesLayout.setHorizontalGroup(
            jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonInsertPilot)
                .addGap(351, 351, 351)
                .addComponent(jButtonModificaPilot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBorraPilot)
                .addGap(20, 20, 20))
            .addGroup(jPanelDadesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextNomPilot, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextEmailPilot, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addComponent(jScrollPane1)
            .addGroup(jPanelDadesLayout.createSequentialGroup()
                .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDadesLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadesLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButtonInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonModificar)))
                        .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextNumMecanics, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxCampio))
                            .addGroup(jPanelDadesLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButtonBorrar)))
                        .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadesLayout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMostrarTotsEquips)))
                        .addGap(18, 18, 18)
                        .addComponent(jTextPressupost, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jComboBoxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanelDadesLayout.setVerticalGroup(
            jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextNumMecanics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextPressupost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jCheckBoxCampio)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonMostrarTotsEquips))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNomPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextEmailPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertPilot)
                    .addComponent(jButtonModificaPilot)
                    .addComponent(jButtonBorraPilot))
                .addGroup(jPanelDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadesLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jComboBoxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelExternLayout = new javax.swing.GroupLayout(jPanelExtern);
        jPanelExtern.setLayout(jPanelExternLayout);
        jPanelExternLayout.setHorizontalGroup(
            jPanelExternLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExternLayout.createSequentialGroup()
                .addComponent(jPanelDades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelExternLayout.setVerticalGroup(
            jPanelExternLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelDades.getAccessibleContext().setAccessibleName("Informació");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelExtern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelExtern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelExtern.getAccessibleContext().setAccessibleName("Informació");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomPilotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomPilotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomPilotActionPerformed

    private void jButtonMostrarTotsEquipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTotsEquipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMostrarTotsEquipsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    public JButton getjButtonBorraPilot() {
        return jButtonBorraPilot;
    }

    public JButton getjButtonBorrar() {
        return jButtonBorrar;
    }

    public JButton getjButtonInsertPilot() {
        return jButtonInsertPilot;
    }

    public JButton getjButtonInsertar() {
        return jButtonInsertar;
    }

    public JButton getjButtonModificaPilot() {
        return jButtonModificaPilot;
    }

    public JButton getjButtonModificar() {
        return jButtonModificar;
    }

    public JCheckBox getjCheckBoxCampio() {
        return jCheckBoxCampio;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public JTextField getjTextDorsal() {
        return jTextDorsal;
    }

    public JTextField getjTextEmailPilot() {
        return jTextEmailPilot;
    }

    public JTextField getjTextEquip() {
        return jTextEquip;
    }

    public JTextField getjTextNomPilot() {
        return jTextNomPilot;
    }

    public JTextField getjTextNumMecanics() {
        return jTextNumMecanics;
    }

    public JTextField getjTextPressupost() {
        return jTextPressupost;
    }

    public JComboBox<EquipF1> getjComboBox1() {
        return jComboBox1;
    }
    
    public int contarFiles() {
        int files = getjTable1().getRowCount();
        return files;
    }

    public JButton getjButtonMostrarTotsEquips() {
        return jButtonMostrarTotsEquips;
    }

    public JComboBox<String> getjComboBoxOrdenar() {
        return jComboBoxOrdenar;
    }

//    //per carregar un JComboBox a partir d'un Tresset que conté les dades 
//    public static void loadCombobox(Collection resultSet, JComboBox combo) {
//        combo.setModel(new DefaultComboBoxModel((resultSet != null ? resultSet.toArray() : new Object[]{})));
//    }

    public FormulaBean getFormulaBean1() {
        return formulaBean1;
    }

    public void setFormulaBean1(FormulaBean formulaBean1) {
        this.formulaBean1 = formulaBean1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private formulabean.FormulaBean formulaBean1;
    private javax.swing.JButton jButtonBorraPilot;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonInsertPilot;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonModificaPilot;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonMostrarTotsEquips;
    private javax.swing.JCheckBox jCheckBoxCampio;
    private javax.swing.JComboBox<EquipF1> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelDades;
    private javax.swing.JPanel jPanelExtern;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextDorsal;
    private javax.swing.JTextField jTextEmailPilot;
    private javax.swing.JTextField jTextEquip;
    private javax.swing.JTextField jTextNomPilot;
    private javax.swing.JTextField jTextNumMecanics;
    private javax.swing.JTextField jTextPressupost;
    // End of variables declaration//GEN-END:variables
}
